table roles
	lineageTag: f4a091c7-bd4a-4ac7-931d-22685c42f869

	measure 'Officer Count' = DISTINCTCOUNT(roles[name])
		formatString: 0
		lineageTag: 0f09c78d-ff41-443a-9958-1b66b3948a4a

	column company_number
		dataType: int64
		formatString: 0
		lineageTag: 674c5e0a-6c8e-4bf9-b0fe-694827c255e7
		summarizeBy: none
		sourceColumn: company_number

		annotation SummarizationSetBy = Automatic

	column district
		dataType: string
		lineageTag: d9e3a6fa-0ed3-4347-a55d-4e3c14489e1a
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column accountant
		dataType: string
		lineageTag: 617a57af-5b22-4062-80ff-86e1ae3e472b
		summarizeBy: none
		sourceColumn: accountant

		annotation SummarizationSetBy = Automatic

	column role_key
		dataType: string
		lineageTag: 9fd29353-68fb-48da-88b1-c3581640a8ec
		summarizeBy: none
		sourceColumn: role_key

		annotation SummarizationSetBy = Automatic

	column role_family
		dataType: string
		lineageTag: 5f63553d-0c31-4c64-8910-b61169b74311
		summarizeBy: none
		sourceColumn: role_family

		annotation SummarizationSetBy = Automatic

	column appointed_before
		dataType: dateTime
		formatString: Long Date
		lineageTag: 795d78ec-01ea-405f-9519-dac964b269bb
		summarizeBy: none
		sourceColumn: appointed_before

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointed_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: d7f25167-cfff-4ee3-9e45-3e2540059f07
		summarizeBy: none
		sourceColumn: appointed_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointment_verification_end_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3206a36-1d06-4a28-8b0d-349877b508b8
		summarizeBy: none
		sourceColumn: appointment_verification_end_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointment_verification_start_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: d276c7ee-e50e-455d-af98-51ec68c766b6
		summarizeBy: none
		sourceColumn: appointment_verification_start_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointment_verification_statement_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8dde0551-7a1d-436b-82a9-b9822288b7a4
		summarizeBy: none
		sourceColumn: appointment_verification_statement_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointment_verification_statement_due_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6d21ba7-7027-4fd4-ac43-f3a66c4dc44d
		summarizeBy: none
		sourceColumn: appointment_verification_statement_due_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column as_of_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 426a64c5-c8b8-45c5-8502-1c1374eca94b
		summarizeBy: none
		sourceColumn: as_of_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column authorised_corporate_service_provider_name
		dataType: string
		lineageTag: f4fb2f3c-2e57-443c-920f-eef1399e8ccd
		summarizeBy: none
		sourceColumn: authorised_corporate_service_provider_name

		annotation SummarizationSetBy = Automatic

	column ceased
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9562edc5-05b8-400d-a917-682ba1e3de99
		summarizeBy: none
		sourceColumn: ceased

		annotation SummarizationSetBy = Automatic

	column ceased_on
		dataType: string
		lineageTag: 5e155898-cd98-40b1-b8aa-7f06cf0d496e
		summarizeBy: none
		sourceColumn: ceased_on

		annotation SummarizationSetBy = Automatic

	column company_in_scope
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 914db08c-1baf-43d1-a423-db4f4611be1b
		summarizeBy: none
		sourceColumn: company_in_scope

		annotation SummarizationSetBy = Automatic

	column current_record
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 76eee3e0-8f5e-438a-b96d-16acaef0a0b5
		summarizeBy: none
		sourceColumn: current_record

		annotation SummarizationSetBy = Automatic

	column date_or_retrieval_quality_issues
		dataType: string
		lineageTag: f3ca1464-635a-4dab-a3f5-440e014145ee
		summarizeBy: none
		sourceColumn: date_or_retrieval_quality_issues

		annotation SummarizationSetBy = Automatic

	column days_until_published_due_date
		dataType: int64
		formatString: 0
		lineageTag: da7bb017-cc48-4869-9b0c-aadf6045d332
		summarizeBy: sum
		sourceColumn: days_until_published_due_date

		annotation SummarizationSetBy = Automatic

	column detail_appointment_verification_end_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9fdf6b56-3078-43e2-a316-f755825dcc60
		summarizeBy: none
		sourceColumn: detail_appointment_verification_end_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column detail_appointment_verification_start_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5917ebaf-b8b0-4b0e-9c18-b353602a9f50
		summarizeBy: none
		sourceColumn: detail_appointment_verification_start_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column detail_appointment_verification_statement_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 153a9335-6d41-4cae-a32a-28a67b2a2385
		summarizeBy: none
		sourceColumn: detail_appointment_verification_statement_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column detail_appointment_verification_statement_due_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f2e66ab-cbe7-4c54-986e-350d25e79fd8
		summarizeBy: none
		sourceColumn: detail_appointment_verification_statement_due_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column detail_authorised_corporate_service_provider_name
		dataType: string
		lineageTag: 0b02a658-e087-4a3d-816b-c7d7c232767b
		summarizeBy: none
		sourceColumn: detail_authorised_corporate_service_provider_name

		annotation SummarizationSetBy = Automatic

	column detail_identity_verified_on
		dataType: string
		lineageTag: 60a4a5b9-7bf5-456d-85e9-a9fbe7356664
		summarizeBy: none
		sourceColumn: detail_identity_verified_on

		annotation SummarizationSetBy = Automatic

	column detail_retrieved_at_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: 1bbde1cc-a522-4ce1-8122-093ade85f6d8
		summarizeBy: none
		sourceColumn: detail_retrieved_at_utc

		annotation SummarizationSetBy = Automatic

	column detail_status
		dataType: string
		lineageTag: 431b9f32-502b-4aa0-840d-ce95e4232e32
		summarizeBy: none
		sourceColumn: detail_status

		annotation SummarizationSetBy = Automatic

	column detail_verification_object_present
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 14705569-caf8-49ce-96bf-4dbe373416b4
		summarizeBy: none
		sourceColumn: detail_verification_object_present

		annotation SummarizationSetBy = Automatic

	column eligible_current_role
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7e3518fd-64af-4ea6-b1c1-d89de875ce88
		summarizeBy: none
		sourceColumn: eligible_current_role

		annotation SummarizationSetBy = Automatic

	column identity_verification_interpretation
		dataType: string
		lineageTag: 06647416-8a92-4382-9262-580fbbccea6e
		summarizeBy: none
		sourceColumn: identity_verification_interpretation

		annotation SummarizationSetBy = Automatic

	column identity_verified_on
		dataType: string
		lineageTag: db5a0d68-0b86-411c-9fe4-642717f1741e
		summarizeBy: none
		sourceColumn: identity_verified_on

		annotation SummarizationSetBy = Automatic

	column interpretation_quality
		dataType: string
		lineageTag: bbbbb66a-25a0-4356-b342-5b990884a2d9
		summarizeBy: none
		sourceColumn: interpretation_quality

		annotation SummarizationSetBy = Automatic

	column list_appointment_verification_end_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 08b99195-7e8f-4c6b-8d10-e46b353d9eb2
		summarizeBy: none
		sourceColumn: list_appointment_verification_end_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column list_appointment_verification_start_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: b5f52d50-cfab-4688-9b1a-686d63367adf
		summarizeBy: none
		sourceColumn: list_appointment_verification_start_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column list_appointment_verification_statement_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0f119a9-15a0-4ae2-b9d4-f83aa1a92066
		summarizeBy: none
		sourceColumn: list_appointment_verification_statement_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column list_appointment_verification_statement_due_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9f564ba-31e1-4c58-88ca-563310b5f066
		summarizeBy: none
		sourceColumn: list_appointment_verification_statement_due_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column list_authorised_corporate_service_provider_name
		dataType: string
		lineageTag: df38be6a-f232-469e-a30c-efc5b6fefc88
		summarizeBy: none
		sourceColumn: list_authorised_corporate_service_provider_name

		annotation SummarizationSetBy = Automatic

	column list_complete
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 70c127f3-f61b-4445-8149-c8b3ba67603f
		summarizeBy: none
		sourceColumn: list_complete

		annotation SummarizationSetBy = Automatic

	column list_identity_verified_on
		dataType: string
		lineageTag: 088e38d9-3d14-49df-9c96-f36565ce2b13
		summarizeBy: none
		sourceColumn: list_identity_verified_on

		annotation SummarizationSetBy = Automatic

	column list_retrieved_at_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: 07da50d1-ea9e-49d8-affd-3c4589ab86df
		summarizeBy: none
		sourceColumn: list_retrieved_at_utc

		annotation SummarizationSetBy = Automatic

	column list_source_url
		dataType: string
		lineageTag: b0e8957d-d6cb-457a-bac8-f27ea88662cc
		summarizeBy: none
		sourceColumn: list_source_url

		annotation SummarizationSetBy = Automatic

	column list_verification_object_present
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6e026526-ff51-4660-8107-b5f848b56800
		summarizeBy: none
		sourceColumn: list_verification_object_present

		annotation SummarizationSetBy = Automatic

	column manual_review_candidate
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5edf5666-8dcd-4994-b4a8-a1f9207f4e1e
		summarizeBy: none
		sourceColumn: manual_review_candidate

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a41bc06b-08eb-4e58-af8b-543afca0045a
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column notified_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: c1705c37-8302-4f05-9c2d-45fc87ce3be4
		summarizeBy: none
		sourceColumn: notified_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column observed_verification_field_names
		dataType: string
		lineageTag: 23cec995-0db6-4a50-917e-4ae3ebb7d4fc
		summarizeBy: none
		sourceColumn: observed_verification_field_names

		annotation SummarizationSetBy = Automatic

	column officer_appointments_link
		dataType: string
		lineageTag: 22216c58-1188-4c37-b4bc-af9dba7c4925
		summarizeBy: none
		sourceColumn: officer_appointments_link

		annotation SummarizationSetBy = Automatic

	column officer_current_company_count_in_batch
		dataType: int64
		formatString: 0
		lineageTag: 21c6f339-009b-4e58-a744-6641a8eca5ca
		summarizeBy: sum
		sourceColumn: officer_current_company_count_in_batch

		annotation SummarizationSetBy = Automatic

	column officer_id
		dataType: string
		lineageTag: 3ccaaa29-92cb-40d7-9973-a73d00716d6c
		summarizeBy: none
		sourceColumn: officer_id

		annotation SummarizationSetBy = Automatic

	column other_current_company_numbers_in_batch
		dataType: string
		lineageTag: 0dff03aa-7848-4bc4-93e7-632cf1f6cb8f
		summarizeBy: none
		sourceColumn: other_current_company_numbers_in_batch

		annotation SummarizationSetBy = Automatic

	column public_register_people_url
		dataType: string
		lineageTag: c11a656e-b8a8-4dc3-9ee5-8f856835b3fa
		summarizeBy: none
		sourceColumn: public_register_people_url

		annotation SummarizationSetBy = Automatic

	column published_due_date_bucket
		dataType: string
		lineageTag: 52f34585-6130-49bd-93ca-fc03b3c6d332
		summarizeBy: none
		sourceColumn: published_due_date_bucket

		annotation SummarizationSetBy = Automatic

	column published_due_date_has_passed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ddd87621-922a-46e5-b4fc-cc979dea6559
		summarizeBy: none
		sourceColumn: published_due_date_has_passed

		annotation SummarizationSetBy = Automatic

	column published_due_within_14_days
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f55532df-72c1-49cf-a8a1-696b82de7bbb
		summarizeBy: none
		sourceColumn: published_due_within_14_days

		annotation SummarizationSetBy = Automatic

	column published_due_within_30_days
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 29132430-bab4-46c5-b14f-a6bea6e9ce42
		summarizeBy: none
		sourceColumn: published_due_within_30_days

		annotation SummarizationSetBy = Automatic

	column published_due_within_60_days
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 152498aa-30a6-4d3c-87af-aeb02bcb1a3f
		summarizeBy: none
		sourceColumn: published_due_within_60_days

		annotation SummarizationSetBy = Automatic

	column record_id_is_synthetic
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 23b0b8fd-dcc6-49d1-bd2d-4ce055ece527
		summarizeBy: none
		sourceColumn: record_id_is_synthetic

		annotation SummarizationSetBy = Automatic

	column resigned_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 25a6f64d-e583-4b59-a56c-f6d15bb6b9c5
		summarizeBy: none
		sourceColumn: resigned_on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column review_candidate_within_14_days
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2e936d42-2b50-4688-951a-bc0e2d5a4aad
		summarizeBy: none
		sourceColumn: review_candidate_within_14_days

		annotation SummarizationSetBy = Automatic

	column review_candidate_within_30_days
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7bcd2266-315a-4a89-a38d-87459ff1250d
		summarizeBy: none
		sourceColumn: review_candidate_within_30_days

		annotation SummarizationSetBy = Automatic

	column review_candidate_within_60_days
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab1e0ae2-2e61-4d11-9bef-3afc6f562f13
		summarizeBy: none
		sourceColumn: review_candidate_within_60_days

		annotation SummarizationSetBy = Automatic

	column role_type
		dataType: string
		lineageTag: 2fd154e1-efa3-45bc-933e-1bf3394e806b
		summarizeBy: none
		sourceColumn: role_type

		annotation SummarizationSetBy = Automatic

	column source_record_id
		dataType: string
		lineageTag: 55c44981-7c02-43b0-9080-92408c558d90
		summarizeBy: none
		sourceColumn: source_record_id

		annotation SummarizationSetBy = Automatic

	column source_record_link
		dataType: string
		lineageTag: 816dfb06-cf0e-4140-a32b-203f210cdd91
		summarizeBy: none
		sourceColumn: source_record_link

		annotation SummarizationSetBy = Automatic

	column source_retrieved_at_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: 985ce3ff-0be4-4cf4-9c25-58e25ff1e3e2
		summarizeBy: none
		sourceColumn: source_retrieved_at_utc

		annotation SummarizationSetBy = Automatic

	column statement_end_interpretation
		dataType: string
		lineageTag: 58459b62-e468-435e-ae18-5b49f1abc8e2
		summarizeBy: none
		sourceColumn: statement_end_interpretation

		annotation SummarizationSetBy = Automatic

	column statement_end_marker_is_9999_12_31
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ee2fed15-2d5f-416f-a75e-bd5abd799847
		summarizeBy: none
		sourceColumn: statement_end_marker_is_9999_12_31

		annotation SummarizationSetBy = Automatic

	column statement_evidence
		dataType: string
		lineageTag: edf18039-399a-4340-b610-7b4e451d27dc
		summarizeBy: none
		sourceColumn: statement_evidence

		annotation SummarizationSetBy = Automatic

	column statement_supply_date_observed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5f701078-6934-49c0-af89-2106458db1f6
		summarizeBy: none
		sourceColumn: statement_supply_date_observed

		annotation SummarizationSetBy = Automatic

	column supported_individual_role
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3b91abde-93ae-4826-a649-81094ec9eb90
		summarizeBy: none
		sourceColumn: supported_individual_role

		annotation SummarizationSetBy = Automatic

	column verification_detail_omits_list_fields
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 55c03099-cc26-4dcb-8305-bdf04f75bac9
		summarizeBy: none
		sourceColumn: verification_detail_omits_list_fields

		annotation SummarizationSetBy = Automatic

	column verification_source
		dataType: string
		lineageTag: ce6b9b07-08e2-45ec-a630-a88ffafac91b
		summarizeBy: none
		sourceColumn: verification_source

		annotation SummarizationSetBy = Automatic

	column verification_sources_disagree
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 81cdfbc9-9b21-46fa-a0e0-1c8e4074895e
		summarizeBy: none
		sourceColumn: verification_sources_disagree

		annotation SummarizationSetBy = Automatic

	column 'Needs Verification' =
			
			VAR DueDate =
			    COALESCE(
			        roles[detail_appointment_verification_statement_due_on],
			        roles[list_appointment_verification_statement_due_on],
			        roles[appointment_verification_statement_due_on]
			    )
			VAR SuppliedDate =
			    COALESCE(
			        roles[detail_appointment_verification_start_on],
			        roles[list_appointment_verification_start_on],
			        roles[appointment_verification_start_on]
			    )
			RETURN
			IF(
			    roles[eligible_current_role] = TRUE()
			        && NOT ISBLANK(DueDate)
			        && ISBLANK(SuppliedDate),
			    1,
			    0
			)
		formatString: 0
		lineageTag: 8b1a1c4d-3890-409a-94d0-419d5a930701
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition roles = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\CravenData\new_data_validation\ch_full_runs\accountant20\exports\roles.csv"),[Delimiter=",", Columns=73, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"company_number", Int64.Type}, {"district", type text}, {"accountant", type text}, {"role_key", type text}, {"role_family", type text}, {"appointed_before", type date}, {"appointed_on", type date}, {"appointment_verification_end_on", type date}, {"appointment_verification_start_on", type date}, {"appointment_verification_statement_date", type date}, {"appointment_verification_statement_due_on", type date}, {"as_of_date", type date}, {"authorised_corporate_service_provider_name", type text}, {"ceased", type logical}, {"ceased_on", type text}, {"company_in_scope", type logical}, {"current_record", type logical}, {"date_or_retrieval_quality_issues", type text}, {"days_until_published_due_date", Int64.Type}, {"detail_appointment_verification_end_on", type date}, {"detail_appointment_verification_start_on", type date}, {"detail_appointment_verification_statement_date", type date}, {"detail_appointment_verification_statement_due_on", type date}, {"detail_authorised_corporate_service_provider_name", type text}, {"detail_identity_verified_on", type text}, {"detail_retrieved_at_utc", type datetime}, {"detail_status", type text}, {"detail_verification_object_present", type logical}, {"eligible_current_role", type logical}, {"identity_verification_interpretation", type text}, {"identity_verified_on", type text}, {"interpretation_quality", type text}, {"list_appointment_verification_end_on", type date}, {"list_appointment_verification_start_on", type date}, {"list_appointment_verification_statement_date", type date}, {"list_appointment_verification_statement_due_on", type date}, {"list_authorised_corporate_service_provider_name", type text}, {"list_complete", type logical}, {"list_identity_verified_on", type text}, {"list_retrieved_at_utc", type datetime}, {"list_source_url", type text}, {"list_verification_object_present", type logical}, {"manual_review_candidate", type logical}, {"name", type text}, {"notified_on", type date}, {"observed_verification_field_names", type text}, {"officer_appointments_link", type text}, {"officer_current_company_count_in_batch", Int64.Type}, {"officer_id", type text}, {"other_current_company_numbers_in_batch", type text}, {"public_register_people_url", type text}, {"published_due_date_bucket", type text}, {"published_due_date_has_passed", type logical}, {"published_due_within_14_days", type logical}, {"published_due_within_30_days", type logical}, {"published_due_within_60_days", type logical}, {"record_id_is_synthetic", type logical}, {"resigned_on", type date}, {"review_candidate_within_14_days", type logical}, {"review_candidate_within_30_days", type logical}, {"review_candidate_within_60_days", type logical}, {"role_type", type text}, {"source_record_id", type text}, {"source_record_link", type text}, {"source_retrieved_at_utc", type datetime}, {"statement_end_interpretation", type text}, {"statement_end_marker_is_9999_12_31", type logical}, {"statement_evidence", type text}, {"statement_supply_date_observed", type logical}, {"supported_individual_role", type logical}, {"verification_detail_omits_list_fields", type logical}, {"verification_source", type text}, {"verification_sources_disagree", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

